version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ms-order
        volumes:
            - ./:/var/www
        networks:
            - ms_order_network
            - microservices_network
        depends_on:
            mysql:
                condition: service_healthy
        env_file:
            - .env

    nginx:
        image: nginx:alpine
        container_name: ms-order-nginx
        ports:
            - "8084:84"
        volumes:
            - ./:/var/www
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - ms_order_network
            - microservices_network
        depends_on:
            - app

    mysql:
        image: mysql:8.0
        container_name: ms-order-mysql
        environment:
            MYSQL_DATABASE: ms_order_db
            MYSQL_ROOT_PASSWORD: TVwDQCGIU4huuUB
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ms_order_network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
            interval: 30s
            timeout: 10s
            retries: 5

networks:
    ms_order_network:
        driver: bridge
    microservices_network:
        external: true

volumes:
    mysql_data:
